spring.application.name=web-app
server.port=9000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

spring.thymeleaf.cache=false

gateway.url=http://localhost:8765
user-service.url=${gateway.url}/user-service
order-service.url=${gateway.url}/order-service
payment-service.url=${gateway.url}/payment-service
catalog-service.url=${gateway.url}/catalog-service

gateway.api-key=gateway-api-key
