spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=file://${user.home}/Desktop/mina_projekat/config-repo
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.force-pull=true
